eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/                
         
         

server:
  port: 3010
spring:
   data:
      mongodb:
         host: localhost
         port: 27017
         username: username
         password: password
         database: otp
  

management:
   server:
      port: 3011
   endpoints:
      web:
         exposure:
            include: "*"  
   endpoint:            
      health:
         show-details: "always"   
         
